### ISSUE TITLE
github management

### ISSUE THREAD

**Issue by NickBold** [Technocopia/administration#11]
Kev, would you be able to 

1) close up the /prometheus repository, 
2) create a new repository for non-admin tasks, and
3) move any admin issues into /administration, and everything else into the new non-admin rep?

Thanks.

**Comment by madhephaestus** [comment]
deleted propethisus

**Comment by madhephaestus** [comment]
created https://github.com/Technocopia/Tasks

**Comment by madhephaestus** [comment]
moving tasks cna be done at next meeting
